spring:
  datasource:
    url: jdbc:postgresql://recommend_db:5432/recommendation_db
  
  neo4j:
    uri: bolt://neo4j:7687
  
  data:
    redis:
      host: redis

  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: recommendation-service
    prefer-ip-address: true

server:
  port: 8095

recommendation:
  nlp:
    phobert-service-url: http://phobert-nlp:8096
